### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Jasonlgrd** [andresz1/size-limit-action#110]
It's possible to cut new release please ? 🙏

Thank you !

**Comment by Jasonlgrd** [comment]
@andresz1

**Comment by andresz1** [comment]
Yes! I will try to do it today because the build was failing 🙏🏻

**Comment by Jasonlgrd** [comment]
Ah okey, no worries 😉

**Comment by Jasonlgrd** [comment]
Hey @andresz1 I have fix it here : https://github.com/andresz1/size-limit-action/pull/111

**Comment by Jasonlgrd** [comment]
The size action failed because it's second build that's broken

**Comment by Jasonlgrd** [comment]
Hi @andresz1, do you have some time to do this? Thank you 🙏

**Comment by Mrazator** [comment]
Hi @andresz1, any updates for a new tag? Would like to use the new `package_manager` option, which was merged more than a 1yr ago.

**Comment by tanmayairbase** [comment]
hello @andresz1, bumping this.. thank you 🙏

**Comment by RichWK** [comment]
Hi @andresz1 — would love to use this but `package_manager` not yet being available blocks it for us! Any chance of a new release?

**Comment by andrii-bodnar** [comment]
Hi @andresz1, is there any chance to get it released soon? 

The latest release uses node12, which is deprecated. I see it is already updated in the `master` branch.

**Comment by Jasonlgrd** [comment]
Done in release 1.8.0 🎉
