### ISSUE TITLE
Working directory

### ISSUE THREAD

**Issue by mrsln** [andresz1/size-limit-action#14]
Thank you for the action! It would be awesome if we could set a working/project directory because there are cases when a repo has several projects (a monorepo). Thank you!

**Comment by andresz1** [comment]
Hi @mrsln,

Sure! that's a great idea 👍 thank you for opening the issue. I'll try to add it during this week and I'll let you know 😉 thanks again

**Comment by andresz1** [comment]
Hi again @mrsln,

I checked it and I think that this could be achieved already without setting a `working_dir` 🤔This is an example of how could be used with [lerna](https://github.com/lerna/lerna).

```json
"scripts": {
  "build": "lerna run build",
  "postinstall": "lerna bootstrap",
  "size": "npm run size-build && size-limit",
  "size-build": "npm run build"
},
"size-limit": [{
  "name": "package1",
  "limit": "3 KB",
  "path": "./packages/package1/dist/index.js"
},  {
  "name": "package2",
  "limit": "3 KB",
  "path": "./packages/package2/dist/index.js"
}],
```

Let me know your thoughts.
Thanks!

**Comment by mrsln** [comment]
Hi @andresz1! Thank you for the suggestion! We do use lerna for running Prettier in the pre-commit hook but not for building the projects. It would've been easier if the action supported `working_dir` option but I might try the lerna solution at some point. Thanks again!

**Comment by andresz1** [comment]
Hi @mrsln, I'll close this by now since an example with `lerna` was added. Feel free to reopen or creating a new issue when you try it out! thank you so much.
