### ISSUE TITLE
Feature request: Reduce number of posts

### ISSUE THREAD

**Issue by vincentmacri** [andresz1/size-limit-action#24]
Right now the action posts after every commit on a PR. This causes a lot of messages cluttering the PR comments.

It would be nice if there was an option to have the action either delete or edit the previous comment, to avoid cluttering with lots of comments.

**Comment by vincentmacri** [comment]
I've been trying to implement this myself, and it seems like the best way to do this is to replace approving/requesting changes for pull request reviews with status checks. Instead of posting a pull request review comment, just post a regular comment and update/delete it after each new run.

**Comment by andresz1** [comment]
Hi @vincentmacri, thank you for opening a PR! check comments
