### ISSUE TITLE
Should % changed be compared against base instead of current?

### ISSUE THREAD

**Issue by billyvg** [andresz1/size-limit-action#41]
https://github.com/andresz1/size-limit-action/blob/master/src/SizeLimit.ts#L48

Wouldn't this make more sense to compare against base instead of current?

```
    const value = ((current - base) / base) * 100;
```

If base is 100, and current is 200, then base increased by 100%.

**Comment by andresz1** [comment]
Yes! I think that you are right @billyvg thank you so much!
