### ISSUE TITLE
Error - Couldn't find a package.json file in "/home/runner/work/..."

### ISSUE THREAD

**Issue by kanevk** [andresz1/size-limit-action#44]
I started a new project that is `tsdx` web package. I'm using yarn as a `package` manager.

<img width="1100" alt="Screenshot 2020-11-05 at 10 47 40" src="https://user-images.githubusercontent.com/8972876/98218355-56dd7500-1f54-11eb-8186-62915bf55c71.png">

I believe that issue is because the main branch has no `package.json` - since the current PR is the first PR for this repo and it introduces `package.json`

**Comment by andresz1** [comment]
That's right. It should have the `package.json` and `size-limit`
