### ISSUE TITLE
Crashing out when run as action but not manually.

### ISSUE THREAD

**Issue by The-Code-Monkey** [andresz1/size-limit-action#54]
https://github.com/AW-Web-Design/styled-system/runs/2619264107

here is a link to the github run that keeps failing at the bottom it says.

```
Error parsing size-limit output. The output should be a json.
Error: Unexpected end of JSON input
```

its also asking me to install packages when they are already installed, the config im using has come from tsdx which i have not modified.

**Comment by gtkatakura** [comment]
It is a problem related to your first install of the action because you don't have size-limit for your target branch and when it tries to run it to compare the results, it crashes.

**Comment by andresz1** [comment]
Yes! this happens only on first install. If you merge the PR it should work as expected! feel free to reopen the issue if not
