### ISSUE TITLE
Warning: Unexpected input(s) 'clean_script'

### ISSUE THREAD

**Issue by ezzatron** [andresz1/size-limit-action#66]
I just noticed this when checking the output from the action in [one of my workflows](https://github.com/snout-router/regexp/runs/3856787530?check_suite_focus=true#step:4:1). I think this just stems from the fact that the `v1` tag hasn't had an update since 2020, but I was just following the README.

I'd prefer not to use `andresz1/size-limit-action@master` if possible. Any chance of an update to `v1`, or possibly a new `v2` tag if necessary?

**Comment by drewlustro** [comment]
Just ran into this myself! Seems to work fine by explicitly declaring the version: `andresz1/size-limit-action@v1.5.1`

**Comment by ezzatron** [comment]
Hmm, that didn't work for me. I still get the warning message: https://github.com/snout-router/regexp/pull/12/checks?check_run_id=3921054812#step:4:1 - which makes sense, since the `clean_script` option was added after the `v1.5.1` tag was created: https://github.com/andresz1/size-limit-action/compare/v1.5.1...master.

Unfortunately there is no tag available that contains the change.

**Comment by andresz1** [comment]
Hi @ezzatron could you try the `v1` version please! It will have the latest changes

**Comment by ezzatron** [comment]
@andresz1 Thank you for the tag ❤️ — It looks like the `clean_script` is working now: https://github.com/snout-router/regexp/runs/6753427847?check_suite_focus=true#step:4:30
