### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by SevereCloud** [andresz1/size-limit-action#93]
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: andresz1/size-limit-action

**Comment by UncleSamSwiss** [comment]
By now the action should support node20:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: andresz1/size-limit-action@v1.7.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by Jasonlgrd** [comment]
It's fixed in 1.8.0 🎉
